// SPDX-License-Identifier: GPL-2.0-or-later
using Zeus.Plugin.Wavelog.Adif;

namespace Zeus.Plugin.Wavelog.Tests;

/// <summary>
/// The parser reads what other loggers wrote, so it meets material this plugin
/// did not produce: headers, typed fields, odd casing, ragged whitespace. It
/// must be forgiving about all of that and strict about exactly one thing —
/// the length prefix.
/// </summary>
public class AdifParserTests
{
    [Fact]
    public void Reads_a_single_record()
    {
        var records = AdifParser.Parse("<CALL:6>DL1ABC<BAND:3>20m<EOR>");
        var r = Assert.Single(records);
        Assert.Equal("DL1ABC", r["CALL"]);
        Assert.Equal("20m", r["BAND"]);
    }

    [Fact]
    public void Skips_a_header_ending_in_eoh()
    {
        const string adif = "Generated by something\n<ADIF_VER:5>3.1.4<EOH>\n<CALL:6>DL1ABC<EOR>";
        var r = Assert.Single(AdifParser.Parse(adif));
        Assert.Equal("DL1ABC", r["CALL"]);
        Assert.False(r.ContainsKey("ADIF_VER"));
    }

    [Fact]
    public void Reads_several_records_separated_by_newlines()
    {
        const string adif = "<CALL:6>DL1ABC<EOR>\n<CALL:5>G4XYZ<EOR>\n";
        var records = AdifParser.Parse(adif);
        Assert.Equal(2, records.Count);
        Assert.Equal("G4XYZ", records[1]["CALL"]);
    }

    [Fact]
    public void Field_names_are_normalised_to_upper_case()
    {
        var r = Assert.Single(AdifParser.Parse("<call:6>DL1ABC<eor>"));
        Assert.Equal("DL1ABC", r["CALL"]);
    }

    [Fact]
    public void Accepts_the_typed_field_form()
    {
        // <NAME:len:TYPE> is legal ADIF and appears in real exports.
        var r = Assert.Single(AdifParser.Parse("<FREQ:9:N>14.074000<EOR>"));
        Assert.Equal("14.074000", r["FREQ"]);
    }

    [Fact]
    public void The_length_prefix_wins_over_any_delimiter_in_the_value()
    {
        // This is the whole point of the format: a value containing '<' or '>'
        // is read by count, not by scanning.
        var r = Assert.Single(AdifParser.Parse("<COMMENT:10>a <b> c &d<EOR>"));
        Assert.Equal("a <b> c &d", r["COMMENT"]);
    }

    [Fact]
    public void Reads_utf8_byte_lengths_not_character_counts()
    {
        var r = Assert.Single(AdifParser.Parse("<COMMENT:7>grüße<EOR>"));
        Assert.Equal("grüße", r["COMMENT"]);
    }

    [Fact]
    public void Zero_length_fields_are_kept_as_empty()
    {
        var r = Assert.Single(AdifParser.Parse("<CALL:6>DL1ABC<COMMENT:0><EOR>"));
        Assert.Equal("", r["COMMENT"]);
    }

    [Fact]
    public void Trailing_material_without_eor_is_ignored_rather_than_half_imported()
    {
        // A truncated file should not produce a partial QSO that looks real.
        var records = AdifParser.Parse("<CALL:6>DL1ABC<EOR><CALL:5>G4XYZ");
        Assert.Single(records);
    }

    [Fact]
    public void A_length_running_past_the_end_is_rejected_loudly()
    {
        Assert.Throws<AdifFormatException>(() => AdifParser.Parse("<CALL:99>DL1ABC<EOR>"));
    }

    [Fact]
    public void A_non_numeric_length_is_rejected_loudly()
    {
        Assert.Throws<AdifFormatException>(() => AdifParser.Parse("<CALL:xx>DL1ABC<EOR>"));
    }

    [Fact]
    public void Empty_input_yields_no_records()
        => Assert.Empty(AdifParser.Parse("   \n  "));

    // ---- round trip ---------------------------------------------------------

    [Fact]
    public void A_record_this_plugin_wrote_reads_back_identically()
    {
        var entry = new Zeus.Plugins.Contracts.Extensions.LogbookEntrySnapshot(
            Id: "1",
            QsoDateTimeUtc: new DateTime(2026, 8, 24, 9, 5, 3, DateTimeKind.Utc),
            Callsign: "dl1abc", Name: "Karl", FrequencyMhz: 14.074, Band: "20m",
            Mode: "USB", RstSent: "59", RstRcvd: "57", Grid: "JO31",
            Country: null, Dxcc: null, CqZone: null, ItuZone: null, State: null,
            Comment: "a <tricky> comment", CreatedUtc: DateTime.UtcNow);

        var r = Assert.Single(AdifParser.Parse(AdifMapper.ToRecord(entry)));

        Assert.Equal("DL1ABC", r["CALL"]);
        Assert.Equal("20260824", r["QSO_DATE"]);
        Assert.Equal("090503", r["TIME_ON"]);
        Assert.Equal("SSB", r["MODE"]);
        Assert.Equal("USB", r["SUBMODE"]);
        Assert.Equal("14.074000", r["FREQ"]);
        Assert.Equal("a <tricky> comment", r["COMMENT"]);
    }
}
